<#
.SYNOPSIS
    Takes a snapshot, compares it against the committed baseline and writes the drift report.

.DESCRIPTION
    The only part of this module that reads files, reaches the gallery or imports a module.
    After the pure comparison it carries firstSeen forward from the previous api-drift.json and
    projects each raw vendor type into the CLR type the generator would emit.

    api-surface.json is written only with -UpdateBaseline, always through
    ConvertTo-M365DSCApiSurfaceJson. A second serializer would rewrite the whole file.

.PARAMETER RepositoryRoot
    Specifies the root of the Microsoft365DSC repository. Defaults to the parent of this module.

.PARAMETER BaselinePath
    Specifies the committed api-surface.json.

.PARAMETER DriftPath
    Specifies where api-drift.json is written.

.PARAMETER MarkdownPath
    Specifies where the Markdown report is written. Omitted means no Markdown is written.

.PARAMETER SchemaCachePath
    Specifies DscSchemaCache.json, which the build regenerates.

.PARAMETER ExclusionPath
    Specifies exclusions.json.

.PARAMETER Current
    Specifies an already-taken snapshot, which skips the acquire step.

.PARAMETER UpdateBaseline
    Indicates that the current snapshot replaces the committed baseline.

.PARAMETER SkipGalleryLookup
    Indicates that no dependency is looked up in the gallery.

.PARAMETER RunDate
    Specifies the date stamped on a finding seen for the first time. Defaults to today in UTC.

.EXAMPLE
    Invoke-M365DSCApiSurfaceCheck

.EXAMPLE
    Invoke-M365DSCApiSurfaceCheck -UpdateBaseline -SkipGalleryLookup

.OUTPUTS
    An ordered dictionary with Findings, Coverage, Backlog, Summary and the paths written.
#>
function Invoke-M365DSCApiSurfaceCheck
{
    [CmdletBinding()]
    [OutputType([System.Collections.Specialized.OrderedDictionary])]
    param
    (
        [Parameter()]
        [System.String]
        $RepositoryRoot = (Join-Path -Path $PSScriptRoot -ChildPath '../../..' -Resolve),

        [Parameter()]
        [System.String]
        $BaselinePath,

        [Parameter()]
        [System.String]
        $DriftPath,

        [Parameter()]
        [System.String]
        $MarkdownPath,

        [Parameter()]
        [System.String]
        $SchemaCachePath,

        [Parameter()]
        [System.String]
        $ExclusionPath,

        [Parameter()]
        [AllowNull()]
        [System.Object]
        $Current,

        [Parameter()]
        [switch]
        $UpdateBaseline,

        [Parameter()]
        [switch]
        $SkipGalleryLookup,

        [Parameter()]
        [System.String]
        $RunDate
    )

    $defaults = @{
        BaselinePath    = 'Utilities/ApiSurface/api-surface.json'
        DriftPath       = 'Utilities/ApiSurface/api-drift.json'
        SchemaCachePath = 'Modules/Microsoft365DSC/DscSchemaCache.json'
        ExclusionPath   = 'Utilities/ApiSurface/exclusions.json'
    }

    foreach ($name in $defaults.Keys)
    {
        if ([System.String]::IsNullOrEmpty((Get-Variable -Name $name -ValueOnly)))
        {
            Set-Variable -Name $name -Value (Join-Path -Path $RepositoryRoot -ChildPath $defaults[$name])
        }
    }

    if ([System.String]::IsNullOrEmpty($RunDate))
    {
        $RunDate = [System.DateTime]::UtcNow.ToString('yyyy-MM-dd', [System.Globalization.CultureInfo]::InvariantCulture)
    }

    if (-not (Test-Path -Path $SchemaCachePath))
    {
        throw "'$SchemaCachePath' does not exist. It is gitignored and regenerated by the build, so run Utilities/Build-Microsoft365DSC.ps1 and Utilities/New-M365DSCDscSchemaCache.ps1 first."
    }

    if ($null -eq $Current)
    {
        $Current = Get-M365DSCApiSurface -RepositoryRoot $RepositoryRoot -SkipGalleryLookup:$SkipGalleryLookup
    }

    $baseline = $Current
    if (Test-Path -Path $BaselinePath)
    {
        $baseline = Get-Content -Path $BaselinePath -Raw | ConvertFrom-Json
    }
    else
    {
        Write-Warning -Message "'$BaselinePath' does not exist. The current snapshot is compared against itself, which reports no vendor drift."
    }

    $exclusion = $null
    if (Test-Path -Path $ExclusionPath)
    {
        $exclusion = Get-Content -Path $ExclusionPath -Raw | ConvertFrom-Json
    }

    $resourcePath = Join-Path -Path $RepositoryRoot -ChildPath 'Modules/Microsoft365DSC/DscResources'
    $origin = @(Get-ResourceOriginSurface -ResourcePath $resourcePath)
    $excludedProperty = Get-ExcludedPropertyMap -ResourcePath $resourcePath
    $schemaKeyword = Get-SchemaKeywordMap -Path $SchemaCachePath

    $previous = @()
    if (Test-Path -Path $DriftPath)
    {
        $previous = @((Get-Content -Path $DriftPath -Raw | ConvertFrom-Json).findings)
    }

    $result = Compare-M365DSCApiSurface -Baseline $baseline `
        -Current $Current `
        -Origin $origin `
        -SchemaKeyword $schemaKeyword `
        -Exclusion $exclusion `
        -ExcludedProperty $excludedProperty `
        -PreviousFinding $previous `
        -RunDate $RunDate

    Add-FindingClrType -Finding $result.Findings -RepositoryRoot $RepositoryRoot

    $drift = [ordered]@{
        formatVersion = 1
        baseline      = [System.String] $baseline.capturedAt
        current       = [System.String] $Current.capturedAt
        summary       = $result.Summary
        findings      = @($result.Findings)
        coverage      = @($result.Coverage)
    }

    $null = New-Item -Path (Split-Path -Path $DriftPath -Parent) -ItemType Directory -Force -ErrorAction SilentlyContinue
    [System.IO.File]::WriteAllText($DriftPath, (ConvertTo-M365DSCApiSurfaceJson -Surface $drift), [System.Text.UTF8Encoding]::new($false))

    if (-not [System.String]::IsNullOrEmpty($MarkdownPath))
    {
        $markdown = (Format-DriftMarkdown -Result $result) -replace "`r`n", "`n" -replace "`n", "`r`n"
        [System.IO.File]::WriteAllText($MarkdownPath, $markdown, [System.Text.UTF8Encoding]::new($false))
    }

    if ($UpdateBaseline)
    {
        [System.IO.File]::WriteAllText($BaselinePath, (ConvertTo-M365DSCApiSurfaceJson -Surface $Current), [System.Text.UTF8Encoding]::new($false))
    }

    return [ordered]@{
        Findings     = $result.Findings
        Coverage     = $result.Coverage
        Backlog      = $result.Backlog
        Summary      = $result.Summary
        DriftPath    = $DriftPath
        MarkdownPath = $MarkdownPath
        BaselinePath = $BaselinePath
    }
}

<#
.SYNOPSIS
    Projects the raw vendor type on each finding into the CLR type the generator would emit.

.DESCRIPTION
    The finding contract wants System.Boolean with a nullable flag, which only the resource
    generator's New-M365DSCPropertyModel produces. Doing it here keeps the differ free of module
    imports. A finding whose 'to' carries no vendor type is left alone.

.PARAMETER Finding
    Specifies the findings to enrich in place.

.PARAMETER RepositoryRoot
    Specifies the root of the Microsoft365DSC repository.
#>
function Add-FindingClrType
{
    [CmdletBinding()]
    [OutputType([System.Void])]
    param
    (
        [Parameter()]
        [AllowEmptyCollection()]
        [System.Object[]]
        $Finding = @(),

        [Parameter(Mandatory = $true)]
        [System.String]
        $RepositoryRoot
    )

    $candidates = @($Finding | Where-Object -FilterScript {
            $null -ne $_.to -and -not [System.String]::IsNullOrEmpty([System.String] $_.to.vendorType)
        })

    if ($candidates.Count -eq 0)
    {
        return
    }

    $generator = Get-M365DSCApiSurfaceGenerator -RepositoryRoot $RepositoryRoot

    foreach ($item in $candidates)
    {
        $model = & $generator {
            param($Name, $Type, $IsArray, $EnumValues)
            New-M365DSCPropertyModel -Name $Name -Type $Type -IsArray $IsArray -EnumValues $EnumValues
        } ([System.String] $item.property) ([System.String] $item.to.vendorType) ([System.Boolean] $item.to.isArray) ([System.String[]] @($item.to.enum))

        $item.to['clrType'] = [System.String] $model.ClrType
        $item.to['nullable'] = $model.ClrType -like 'System.Nullable*'
    }
}

<#
.SYNOPSIS
    Reads the excludedProperties array of every resource.

.PARAMETER ResourcePath
    Specifies the folder holding the MSFT_<Name> resource folders.

.OUTPUTS
    A map of resource name to its excludedProperties entries.
#>
function Get-ExcludedPropertyMap
{
    [CmdletBinding()]
    [OutputType([System.Collections.Hashtable])]
    param
    (
        [Parameter(Mandatory = $true)]
        [System.String]
        $ResourcePath
    )

    $map = [System.Collections.Hashtable]::new([System.StringComparer]::OrdinalIgnoreCase)

    foreach ($folder in (Get-ChildItem -Path $ResourcePath -Directory))
    {
        $settingsPath = Join-Path -Path $folder.FullName -ChildPath 'settings.json'
        if (-not (Test-Path -Path $settingsPath))
        {
            continue
        }

        $settings = Get-Content -Path $settingsPath -Raw | ConvertFrom-Json
        $map[($folder.Name -replace '^MSFT_', '')] = @($settings.excludedProperties)
    }

    return $map
}

<#
.SYNOPSIS
    Reads the resource keywords out of DscSchemaCache.json.

.DESCRIPTION
    The cache holds 998 keywords. Resource keywords carry nameMode NameRequired and an
    unprefixed name, while the complex types carry NoName and an MSFT_ prefix.

.PARAMETER Path
    Specifies DscSchemaCache.json.

.OUTPUTS
    A map of resource name to its keyword.
#>
function Get-SchemaKeywordMap
{
    [CmdletBinding()]
    [OutputType([System.Collections.Hashtable])]
    param
    (
        [Parameter(Mandatory = $true)]
        [System.String]
        $Path
    )

    $map = [System.Collections.Hashtable]::new([System.StringComparer]::OrdinalIgnoreCase)

    foreach ($keyword in (Get-Content -Path $Path -Raw | ConvertFrom-Json).keywords)
    {
        if ($keyword.nameMode -ne 'NameRequired')
        {
            continue
        }

        $map[[System.String] $keyword.resourceName] = $keyword
    }

    return $map
}
