[ClassVersion("1.0.0.4"), FriendlyName("SPOTenantSettings")]
class MSFT_SPOTenantSettings : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"),ValueMap{"Yes"},Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Enables OneDrive and SharePoint integration with Microsoft Entra B2B.")] boolean EnableAzureADB2BIntegration;
    [Write, Description("Specifies the lower bound on the compatibility level for new sites.")] uint32 MinCompatibilityLevel;
    [Write, Description("Specifies the upper bound on the compatibility level for new sites.")] uint32 MaxCompatibilityLevel;
    [Write, Description("Removes the search capability from People Picker. Note, recently resolved names will still appear in the list until browser cache is cleared or expired.")] boolean SearchResolveExactEmailOrUPN;
    [Write, Description("When set to true this will disable the ability to use Modern Authentication that leverages ADAL across the tenant.")] boolean OfficeClientADALDisabled;
    [Write, Description("Allows configuring whether users will be able to create anonymous requests for people to upload files regardless of the Share with anyone link configuration setting.")] boolean OneDriveRequestFilesLinkEnabled;
    [Write, Description("Specifies the number of days before a Request files link expires for all OneDrive sites. The value can be from 0 to 730 days. To remove the expiration requirement, set the value to zero (0).")] uint32 OneDriveRequestFilesLinkExpirationInDays;
    [Write, Description("Setting this parameter prevents Office clients using non-modern authentication protocols from accessing SharePoint Online resources.")] boolean LegacyAuthProtocolsEnabled;
    [Write, Description("Specifies the home realm discovery value to be sent to Azure Active Directory (AAD) during the user sign-in process.")] String SignInAccelerationDomain;
    [Write, Description("Lets SharePoint issue a special cookie that will allow this feature to work even when Keep Me Signed In is not selected.")] boolean UsePersistentCookiesForExplorerView;
    [Write, Description("Configure PublicCDN")] boolean PublicCdnEnabled;
    [Write, Description("Configure filetypes allowed for PublicCDN")] String PublicCdnAllowedFileTypes;
    [Write, Description("When set to $true, users aren't able to share with security groups or SharePoint groups.")] boolean UseFindPeopleInPeoplePicker;
    [Write, Description("When set to $true, users aren't able to share with security groups or SharePoint groups.")] boolean NotificationsInSharePointEnabled;
    [Write, Description("Specifies whether an email notification should be sent to the OneDrive for Business owners when an anonymous links are created or changed.")] boolean OwnerAnonymousNotification;
    [Write, Description("When this parameter is set to true, an email notification that user receives when is mentioned, includes the surrounding document context. Set it to false to disable this feature.")] boolean AllowCommentsTextOnEmailEnabled;
    [Write, Description("Enables or disables web property bag update when DenyAddAndCustomizePages is enabled. When AllowWebPropertyBagUpdateWhenDenyAddAndCustomizePagesIsEnabled is set to $true, web property bag can be updated even if DenyAddAndCustomizePages is turned on when the user had AddAndCustomizePages (prior to DenyAddAndCustomizePages removing it).")] Boolean AllowWebPropertyBagUpdateWhenDenyAddAndCustomizePagesIsEnabled;
    [Write, Description("Enables of disables applications running in app-only mode to access IB sites.")] boolean AppBypassInformationBarriers;
    [Write, Description("When the feature is enabled, all guest users are subject to conditional access policy. By default guest users who are accessing SharePoint Online files with pass code are exempt from the conditional access policy.")] boolean ApplyAppEnforcedRestrictionsToAdHocRecipients;
    [Write, Description("Can be used to configure a custom page to show when a user is navigating to a SharePoint Online site that has been archived using Microsoft Syntex Archiving.")] string ArchiveRedirectUrl;
    [Write, Description("The File Type IDs which need to specified to prevent download. Allowed values: TeamsMeetingRecording.")] String BlockDownloadFileTypeIds[];
    [Write, Description("You can block the download of Teams meeting recording files from SharePoint or OneDrive. This allows users to remain productive while addressing the risk of accidental data loss. Users have browser-only access to play the meeting recordings with no ability to download or sync files or access them through apps.")] boolean BlockDownloadFileTypePolicy;
    [Write, Description("Allows blocking of the automated e-mail being sent when somebody uploads a document to a site that's protected with a sensitivity label and their document has a higher priority sensitivity label than the sensitivity label applied to the site.")] boolean BlockSendLabelMismatchEmail;
    [Write, Description("Specifies the number of days before a Request files link expires for all SharePoint sites (not including OneDrive sites). The value can be from 0 to 730 days.")] uint32 CoreRequestFilesLinkExpirationInDays;
    [Write, Description("Enable or disable the Request files link on the core partition for all SharePoint sites (not including OneDrive sites). If this value is not set, Request files will only show for OneDrives with Anyone links enabled.")] boolean CoreRequestFilesLinkEnabled;
    [Write, Description("The DefaultOneDriveInformationBarrierMode sets the information barrier mode for all OneDrive sites. The valid values are: Open, Explicit, Implicit, OwnerModerated, Mixed."), ValueMap{"Open","Explicit","Implicit","OwnerModerated","Mixed"}, Values{"Open","Explicit","Implicit","OwnerModerated","Mixed"}] string DefaultOneDriveInformationBarrierMode;
    [Write, Description("Allows temporary whiteboard collaboration for anonymous meeting participants during Teams meetings."), ValueMap{"Unspecified","On","Off"}, Values{"Unspecified","On","Off"}] String AllowAnonymousMeetingParticipantsToAccessWhiteboards;
    [Write, Description("This parameter exempts users in the specified security groups from this policy so that they can download meeting recording files.")] String ExcludedBlockDownloadGroupIds[];
    [Write, Description("Use this to turn off setting the default sensitivity label for a document library.")] Boolean DisableDocumentLibraryDefaultLabeling;
    [Write, Description("Enables or disables users in the organization to authenticate SharePoint applications using popups.")] Boolean IsEnableAppAuthPopUpEnabled;
    [Write, Description("Specifies the number of days to keep versions when version history limits are managed manually.")] UInt32 ExpireVersionsAfterDays;
    [Write, Description("Specifies the number of major versions to keep when version history limits are managed manually.")] UInt32 MajorVersionLimit;
    [Write, Description("Enables or disables AutoExpiration version trim for document libraries. Parameter `ExpireVersionsAfterDays` is required when `EnableAutoExpirationVersionTrim` is false. Set `ExpireVersionsAfterDays` to 0 for NoExpiration, set it to greater or equal 30 for ExpireAfter.")] Boolean EnableAutoExpirationVersionTrim;
    [Write, Description("Use this parameter to disable or enable Viva Connections analytics.")] Boolean DisableVivaConnectionsAnalytics;
    [Write, Description("Determines whether guest users can be site collection administrators on SharePoint sites. Valid values are: Unspecified, On, Off"), ValueMap{"Unspecified","On","Off"}, Values{"Unspecified","On","Off"}] String CoreBlockGuestsAsSiteAdmin;
    [Write, Description("Sets whether Whiteboard is enabled or disabled for OneDrive for Business users.")] Boolean IsWBFluidEnabled;
    [Write, Description("Gets or sets a value to specify whether CollabMeetingNotes Fluid Framework is enabled.")] Boolean IsCollabMeetingNotesFluidEnabled;
    [Write, Description("Gets or sets the IBImplicitGroupBased value.")] Boolean IBImplicitGroupBased;
    [Write, Description("Displays the Open in desktop option for files synchronized with the OneDrive sync app.")] Boolean ShowOpenInDesktopOptionForSyncedFiles;
    [Write, Description("Allows showing group suggestions for information barriers in the People Picker.")] Boolean ShowPeoplePickerGroupSuggestionsForIB;
    [Write, Description("Enables reduced session timeout for temporary URLs used by apps for document download scenarios. Reduction occurs when an app redeeming an IP address does not match the original requesting IP. The default value is 15 minutes if ReduceTempTokenLifetimeValue is not set.")] Boolean ReduceTempTokenLifetimeEnabled;
    [Write, Description("Optional value, in minutes, to set the session timeout for temporary URLs. Allowed values are from 5 to 15. The default value is 15 minutes.")] UInt32 ReduceTempTokenLifetimeValue;
    [Write, Description("Controls whether viewers commenting on media items is disabled or not.")] Boolean ViewersCanCommentOnMediaDisabled;
    [Write, Description("Specifies a help link shown when Conditional Access Policy blocks a user. The value must be a valid URL starting with http:// or https://.")] String ConditionalAccessPolicyErrorHelpLink;
    [Write, Description("Specifies a URL appended to the external sharing policy block message to direct users to internal guidance or request portals.")] String CustomizedExternalSharingServiceUrl;
    [Write, Description("Enables or disables the At A Glance feature in sharing e-mails.")] Boolean IncludeAtAGlanceInShareEmails;
    [Write, Description("Enables or disables mass delete detection notifications.")] Boolean MassDeleteNotificationDisabled;
    [Write, Description("Sets the sharing state for blocking guests as site admin in OneDrive. Valid values are: On, Off, Unspecified"), ValueMap{"On","Off","Unspecified"}] String OneDriveBlockGuestsAsSiteAdmin;
    [Write, Description("Sets the retention period for the recycle bin. The value of Recycle Bin Retention Period must be between 14 and 93. By default it is set to 93.")] UInt32 RecycleBinRetentionPeriod;
    [Write, Description("Enables or disables legacy browser authentication protocols.")] Boolean LegacyBrowserAuthProtocolsEnabled;
    [Write, Description("Enables or disables showing the organization-wide sharing option in the sharing dialog for videos.")] Boolean EnableDiscoverableByOrganizationForVideos;
    [Write, Description("Sets a custom learn more link to inform users denied access due to restricted site access control policy.")] String RestrictedAccessControlforSitesErrorHelpLink;
    [Write, Description("Sets a value to specify whether Workflow 2010 is disabled.")] Boolean Workflow2010Disabled;
    [Write, Description("Sets a value to specify whether the sync button on document libraries is hidden.")] Boolean HideSyncButtonOnDocLib;
    [Write, Description("Sets the default destination for the Stream app launcher tile.")] Sint32 StreamLaunchConfig;
    [Write, Description("Controls whether media reactions are enabled.")] Boolean EnableMediaReactions;
    [Write, Description("Controls whether content security policy is enabled.")] Boolean ContentSecurityPolicyEnforcement;
    [Write, Description("Enables or disables activation of spaces.")] Boolean DisableSpacesActivation;
    [Write, Description("Controls whether apps can bypass the unmanaged device policy.")] Boolean AllowAppsBypassOfUnmanagedDevicePolicy;
    [Write, Description("Allows administrators to prevent specific Adaptive Card Extensions from being added to pages or rendering on pages where they were previously added.")] String DisabledAdaptiveCardExtensionIds[];
    [Write, Description("Enables or disables writing SharePoint News and Announcement notification data to each user's NewsNotificationList.")] Boolean EnableNotificationsSubscriptions;
    [Write, Description("When set to true, a valid request digest is required for state-changing SOAP API calls.")] Boolean EnforceRequestDigest;
    [Write, Description("Sets the Transport Layer Security (TLS) token binding policy setting."), ValueMap{"Audit","None","PassiveEnforcement","StrictEnforcement"}, Values{"Audit","None","PassiveEnforcement","StrictEnforcement"}] String TlsTokenBindingPolicyValue;
    [Write, Description("Sets the authentication context resilience mode."), ValueMap{"DefaultAAD","Disabled","Enabled"}, Values{"DefaultAAD","Disabled","Enabled"}] String AuthContextResilienceMode;
    [Write, Description("Sets the All-Organization Security Group by object ID.")] String AllOrganizationSecurityGroupId;
    [Write, Description("Sets the site templates that receive content type hub synchronization.")] String ContentTypeSyncSiteTemplatesList[];
    [Write, Description("Sets whether webparts that support inserting images, like for example Image or Hero webpart, the Web search (Powered by Bing) should allow choosing external images.")] boolean FilePickerExternalImageSearchEnabled;
    [Write, Description("Defines if the default themes are visible or hidden")] boolean HideDefaultThemes;
    [Write, Description("To enable or disable Sync button on Team sites")] boolean HideSyncButtonOnTeamSite;
    [Write, Description("Allows turning on support for data access in the Viva Connections Adaptive Card Designer.")] boolean IsDataAccessInCardDesignerEnabled;
    [Write, Description("Allow or block external sharing until at least one Office DLP policy scans the content of the file."), ValueMap{"AllowExternalSharing","BlockExternalSharing"}, Values{"AllowExternalSharing","BlockExternalSharing"}] string MarkNewFilesSensitiveByDefault;
    [Write, Description("When the feature is enabled, videos can have transcripts generated on demand or generated automatically in certain scenarios. This is the default because the policy is default on. If a video owner decides they don’t want the transcript, they can always hide or delete it from that video. Possible values: Enabled, Disabled."), ValueMap{"Disabled","Enabled"}, Values{"Disabled","Enabled"}] string MediaTranscription;
    [Write, Description("When the feature is enabled, videos can have transcripts generated automatically on upload. The policy is default on. If a tenant admin decides to disable the feature, he can do so by disabling the policy at tenant level. This feature can not be enabled or disabled at site level. Possible values: Enabled, Disabled."), ValueMap{"Disabled","Enabled"}, Values{"Disabled","Enabled"}] string MediaTranscriptionAutomaticFeatures;
    [Write, Description("Provide GUID for the Web Parts that are to be disabled on the Sharepoint Site")] string DisabledWebPartIds[];
    [Write, Description("This parameter allows site owners to create or update the service principal.")] boolean SiteOwnerManageLegacyServicePrincipalEnabled;
    [Write, Description("Disables or enables the Social Bar. It will give users the ability to like a page, see the number of views, likes, and comments on a page, and see the people who have liked a page.")] boolean SocialBarOnSitePagesDisabled;
    [Write, Description("Set to false to enable a comment section on all site pages, users who have access to the pages can leave comments. Set to true to disable this feature.")] boolean CommentsOnSitePagesDisabled;
    [Write, Description("Boolean indicating if Azure Information Protection (AIP) should be enabled on the tenant.")] boolean EnableAIPIntegration;
    [Write, Description("Allows turning on support for PDFs with sensitivity labels.")] boolean EnableSensitivityLabelForPDF;
    [Write, Description("Determines whether or not we need to include external participants in shared channels for SharePoint access restriction.")] Boolean ExemptNativeUsersFromTenantLevelRestricedAccessControl;
    [Write, Description("List of security groups to include in OneDrive access restrictions")] String AllowSelectSGsInODBListInTenant[];
    [Write, Description("List of security groups to exclude in OneDrive access restrictions")] String DenySelectSGsInODBListInTenant[];
    [Write, Description("List of security groups to exclude in SharePoint access restrictions")] String DenySelectSecurityGroupsInSPSitesList[];
    [Write, Description("List of security groups to include in SharePoint access restrictions.")] String AllowSelectSecurityGroupsInSPSitesList[];
    [Write, Description("The default timezone of a tenant for newly created sites.")] String TenantDefaultTimezone;
    [Write, Description("Gets or sets a value to specify if user checks handle mobile friendly url.")] Boolean MobileFriendlyUrlEnabledInTenant;
    [Write, Description("Gets or sets a value to specify the advanced setting of the conditional access policy.")] Boolean AllowDownloadingNonWebViewableFiles;
    [Write, Description("Prevents users from editing Office files in the browser and copying and pasting Office file contents out of the browser window.")] Boolean AllowEditing;
    [Write, Description("Enables or disables file-level archiving for SharePoint Online sites in the tenant. When set to $false, users can no longer archive files on any site even if the site-level setting is enabled. Existing archived files remain archived and can still be reactivated.")] Boolean AllowFileArchive;
    [Write, Description("Controls whether newly created SharePoint Online sites have file-level archiving enabled by default. Use this together with `-AllowFileArchive $true` when you want new sites to inherit file archiving automatically instead of enabling it site by site.")] Boolean AllowFileArchiveOnNewSitesByDefault;
    [Write, Description("Set whether to hide the sync button on OneDrive for Business sites.")] Boolean HideSyncButtonOnODB;
    [Write, Description("Configure if ACS-based app-only authentication should be disabled or not.")] Boolean DisableCustomAppAuthentication;
    [Write, Description("Guids of out of the box modern list templates to hide when creating a new list.")] String DisabledModernListTemplateIds[];
    [Write, Description("Allows configuring whether personal lists created within the OneDrive for Business site of the user is enabled or disabled in the tenant. If set to $false, personal lists will be allowed to be created in the tenant. If set to $true, it will be disabled in the tenant.")] Boolean DisablePersonalListCreation;
    [Write, Description("Allows configuring whether display name of people who view the file are visible in the property pane of the site in SharePoint site collection.")] Boolean DisplayNamesOfFileViewersInSpo;
    [Write, Description("Allows configuration on whether Fluid components are enabled or disabled in the tenant. If set to $true, then this feature will be enabled on all sites in the tenant. If set to $false, it will be disabled on all sites in the tenant.")] Boolean IsFluidEnabled;
    [Write, Description("Allows configuring whether loop components are enabled or disabled in the tenant. If set to $true, loop components will be allowed to be created in the tenant. If set to $false, it will be disabled in the tenant.")] Boolean IsLoopEnabled;
    [Write, Description("When the feature is enabled, all the add-ins features will be disabled.")] Boolean IsSharePointAddInsDisabled;
    [Write, Description("Indicates whether the newsfeed is allowed on the modern site pages in SharePoint.")] Boolean IsSharePointNewsfeedEnabled;
    [Write, Description("Indicates whether users are allowed to create sites.")] Boolean IsSiteCreationEnabled;
    [Write, Description("Indicates whether the UI commands for creating sites are shown.")] Boolean IsSiteCreationUiEnabled;
    [Write, Description("Indicates whether creating new modern pages is allowed on SharePoint sites.")] Boolean IsSitePagesCreationEnabled;
    [Write, Description("Enables or disables the Knowledge Agent feature tenant-wide. When set to $true, the Knowledge Agent functionality is enabled for the tenant; when set to $false it is disabled. Use this parameter to control tenant-level Knowledge Agent behavior.")] Boolean KnowledgeAgentEnabled;
    [Write, Description("Specifies a list of site collection URLs that should be selected for the tenant Knowledge Agent. Each entry must be a full site URL (for example: https://contoso.sharepoint.com/sites/team1). The cmdlet will resolve each URL to the corresponding site id and configure the tenant Knowledge Agent to target those sites.")] String KnowledgeAgentSelectedSitesList[];
    [Write, Description("Specifies the URL of the redirected site for those site collections which have the locked state 'NoAccess'. The valid values are: '' (default) - Blank by default, this will also remove or clear any value that has been set. Full URL - Example: https://contoso.sharepoint.com/Pages/Locked.aspx")] String NoAccessRedirectUrl;
    [Write, Description("Ensures that an external user can only accept an external sharing invitation with an account matching the invited email address. Note, this only applies to new external users accepting new sharing invitations. Also, the resource owner must share with an organizational or Microsoft account or the external user will be unable to access the resource. ")] Boolean RequireAcceptingAccountMatchInvitedAccount;
    [Write, Description("Permits the use of special characters in file and folder names in SharePoint Online and OneDrive for Business document libraries. The only two characters that can be managed at this time are the # and % characters."), ValueMap{"NoPreference","Allowed","Disallowed"}, Values{"NoPreference","Allowed","Disallowed"}] String SpecialCharactersStateInFileFolderNames;
    [Write, Description("Only accepted value is 'Present'."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the account to authenticate with."), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Secret of the Azure Active Directory application to authenticate with."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Name of the Azure Active Directory tenant used for authentication. Format contoso.onmicrosoft.com")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
